
name: Staging Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./home/ubuntu/myprojectdir/myproject
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

   

    - name: FTP Deploy to WP Engine (Staging)
      uses: ubuntu
      with:
        ftp-server: 52.66.88.231
        ftp-username: ubuntu
        ftp-password: ${{ secrets.TEST }}
        local-dir: ./home/ubuntu/myprojectdir/myproject
